# configuration info for sunburst diagram
---
output:
        name: 'test'
layer:
        layer_width: 7
        sector_width: 3
        end_cap_width: 3

data:
        max_recursion: 18
        # list the valid characters
        alphabet: 'abcdefghijklmnopqrstuvwxyz'
        numbers: '0123456789'
...
