# configuration info for sunburst diagram
---
output:
        name: 'test'
        xdelta: 105
        x: 200
        y: 111.76
layer:
        layer_width: 4.291
        sector_width: 1.839

data:
        max_recursion: 18
        # list the valid characters
        alphabet: 'abcdefghijklmnopqrstuvwxyz'
        numbers: '0123456789'
...
